version: '3'

services:
  feedback_db:
    container_name: feedback_db
    restart: always
    image: postgres:9.6
    volumes:
      - feedback_data:/var/lib/postgresql/data
    env_file:
      - ./feedback.env
  feedback_app:
    container_name: feedback_app
    restart: always
    image: getfider/fider:stable
    ports:
      - "9999:3000"
    env_file: 
      - ./feedback.env
    depends_on:
      - feedback_db

  analytics_db:
    container_name: analytics_db
    image: mariadb
    command: --max-allowed-packet=64MB
    restart: always
    volumes:
      - analytics_db:/var/lib/mysql
    env_file:
      - ./analytics.env
  analytics_app:
    container_name: analytics_app
    image: matomo:fpm-alpine
    restart: always
    links:
      - analytics_db
    volumes:
#      - ./config:/var/www/html/config:rw
#      - ./logs:/var/www/html/logs
      - analytics_matomo:/var/www/html
    env_file:
      - ./analytics.env
  analytics_web:
    container_name: analytics_web
    image: nginx:alpine
    restart: always
    volumes:
      - analytics_matomo:/var/www/html:ro
      - ./matomo.conf:/etc/nginx/conf.d/default.conf:ro
    env_file: 
      - ./blog.env
    ports:
      - 8080:80

  blog_web:
    container_name: blog_web
    image: ghost:3-alpine
    restart: always
    ports:
      - 8090:2368
    env_file: 
      - ./blog.env
  blog_db:
    container_name: blog_db
    image: mysql:5.7
    restart: always

volumes:
  analytics_db:
  analytics_matomo:
  feedback_data: